name: Create a repository tag

#
# Creates a tag with the given version.
#
# TODO: Remove once the common repo is public.
#

inputs:
  token:
    required: true
  tag:
    required: true

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        git config user.name "${AUTHOR_USERNAME}"
        git config user.email "${AUTHOR_EMAIL}"
      env:
        AUTHOR_USERNAME: ${{ github.event.pull_request.user.login }}
        AUTHOR_EMAIL: ${{ github.event.pull_request.user.email }}

    - shell: bash
      run: |
        git tag -a ${TAG_NAME} -m "Version ${TAG_NAME}"
        git push --follow-tags
      env:
        TAG_NAME: ${{ inputs.tag }}
        GITHUB_TOKEN: ${{ inputs.token }}
