name: Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

env:
  NODE_VERSION: 24

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint-title:
    name: Lint PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install action dependencies
        run: npm install --ignore-scripts
        working-directory: .github/actions/lint-pr-title

      - name: Lint PR Title
        uses: ./.github/actions/lint-pr-title
