name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Release versions
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+' # Beta versions
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

permissions:
  contents: read

env:
  NODE_VERSION: 18

jobs:
  publish-npm:
    name: 'NPM'
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Build package
        uses: ./.github/actions/build
        with:
          node: ${{ env.NODE_VERSION }}

      - name: Publish release to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

