name: RL-Secure Workflow
run-name: rl-scanner-only

on:
  merge_group:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checkout-build-scan-only:
    runs-on: ubuntu-latest

    environment: security

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm install

      - name: Create tgz build artifact
        run: |
          tar -czvf auth0-spa-js.tgz *

      - name: Get Artifact Version
        id: get_version
        run: echo "::set-output name=version::$(cat .version)"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Reversing Labs Wrapper Scanner
        env:
          RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
        run: |
          python scripts/rl-wrapper.py \
            --artifact "$(pwd)/auth0-spa-js.tgz" \
            --name "${{ github.event.repository.name }}" \
            --version "${{ steps.get_version.outputs.version }}" \
            --repository "${{ github.repository }}" \
            --commit "${{ github.sha }}" \
            --build-env "GitHub Actions"
        continue-on-error: true

      - name: Find and List violations.txt in /tmp
        run: |
          echo "Searching for violations.txt in /tmp:"
          find /tmp -name 'violations.txt' -print

      - name: Add or Update PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const { promisify } = require('util');
            const readdir = promisify(fs.readdir);
            const prNumber = context.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const header = 'RL-Secure Scanner Results';

            // Search for violations.txt in /tmp/ directories
            async function findFile(dir) {
              try {
                const files = await readdir(dir);
                for (const file of files) {
                  const filePath = path.join(dir, file);
                  const stat = await promisify(fs.stat)(filePath);
                  if (stat.isDirectory()) {
                    const foundFile = await findFile(filePath);
                    if (foundFile) return foundFile;
                  } else if (file === 'violations.txt') {
                    return filePath;
                  }
                }
              } catch (error) {
                console.error('Error reading directory:', error);
              }
              return null;
            }

            (async () => {
              const tmpDir = '/tmp';
              const filePath = await findFile(tmpDir);

              if (filePath) {
                console.log(`Found file at: ${filePath}`);
                const commentBody = fs.readFileSync(filePath, 'utf8');

                const { data: comments } = await github.rest.issues.listComments({
                  owner: repoOwner,
                  repo: repoName,
                  issue_number: prNumber
                });

                const existingComment = comments.find(comment => comment.body.startsWith(header));

                if (existingComment) {
                  await github.rest.issues.updateComment({
                    owner: repoOwner,
                    repo: repoName,
                    comment_id: existingComment.id,
                    body: `${header}\n\n${commentBody}`
                  });
                } else {
                  await github.rest.issues.createComment({
                    owner: repoOwner,
                    repo: repoName,
                    issue_number: prNumber,
                    body: `${header}\n\n${commentBody}`
                  });
                }
              } else {
                console.log('File not found.');
              }
            })();
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
