name: SCA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      pre-scan-commands: "npm install"
      additional-arguments: "--exclude=README.md"
      node-version: 24
    secrets: inherit
