name: 'SPA JS SDK'

on: push

jobs:
  gatsby:
    name: Gatbsy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: spa-js
      - name: Install dependencies
        run: npm ci
        working-directory: spa-js
      - name: Build SPAJS
        run: npm run build
        working-directory: spa-js
      - name: Create App
        run: npx gatsby new my-app
      - name: Install SPA JS
        run: |
          yarn add "../spa-js"
          echo -e "$AUTH0_CONTENT" > src/auth0.js;
          echo -e "$IMPORT_STATEMENT"|cat - src/pages/index.js > /tmp/out && mv /tmp/out src/pages/index.js;
        working-directory: my-app
        env:
          IMPORT_STATEMENT: |
            import './../auth0';
          AUTH0_CONTENT: |
            import { Auth0Client } from '@auth0/auth0-spa-js';
            new Auth0Client({
              domain: 'DOMAIN',
              client_id: 'CLIENT_ID'
            });
      - name: Build App
        run: yarn build
        working-directory: my-app
  react:
    name: React
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: spa-js
      - name: Install dependencies
        run: npm ci
        working-directory: spa-js
      - name: Build SPAJS
        run: npm run build
        working-directory: spa-js
      - name: Create App
        run: npx create-react-app my-app
      - name: Install SPA JS
        run: |
          yarn add "../spa-js"
          echo -e "$AUTH0_CONTENT" > src/auth0.js;
          echo -e "$IMPORT_STATEMENT"|cat - src/index.js > /tmp/out && mv /tmp/out src/index.js;
        working-directory: my-app
        env:
          IMPORT_STATEMENT: |
            import './auth0';
          AUTH0_CONTENT: |
            import { Auth0Client } from '@auth0/auth0-spa-js';
            new Auth0Client({
              domain: 'DOMAIN',
              client_id: 'CLIENT_ID'
            });
      - name: Build App
        run: yarn build
        working-directory: my-app
  vue:
    name: Vue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: spa-js
      - name: Install dependencies
        run: npm ci
        working-directory: spa-js
      - name: Build SPAJS
        run: npm run build
        working-directory: spa-js
      - name: Create App
        run: npx -p @vue/cli vue create my-app -d -m yarn
      - name: Install SPA JS
        run: |
          yarn add "../spa-js"
          echo -e "$AUTH0_CONTENT" > src/auth0.js;
          echo -e "$IMPORT_STATEMENT"|cat - src/main.js > /tmp/out && mv /tmp/out src/main.js;
        working-directory: my-app
        env:
          IMPORT_STATEMENT: |
            import './auth0';
          AUTH0_CONTENT: |
            import { Auth0Client } from '@auth0/auth0-spa-js';
            new Auth0Client({
              domain: 'DOMAIN',
              client_id: 'CLIENT_ID'
            });
      - name: Build App
        run: yarn build
        working-directory: my-app
  angular:
    name: Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: spa-js
      - name: Install dependencies
        run: npm ci
        working-directory: spa-js
      - name: Build SPAJS
        run: npm run build
        working-directory: spa-js
      - name: Create App
        run: npx -p @angular/cli ng new my-app --defaults=true --packageManager=yarn
      - name: Install SPA JS
        run: |
          yarn add "../spa-js"
          echo -e "$AUTH0_CONTENT" > src/auth0.ts;
          echo -e "$IMPORT_STATEMENT"|cat - src/main.ts > /tmp/out && mv /tmp/out src/main.ts;
        working-directory: my-app
        env:
          IMPORT_STATEMENT: |
            import './auth0';
          AUTH0_CONTENT: |
            import { Auth0Client } from '@auth0/auth0-spa-js';
            new Auth0Client({
              domain: 'DOMAIN',
              client_id: 'CLIENT_ID'
            });
      - name: Build App
        run: yarn build
        working-directory: my-app
